// Generated by view binder compiler. Do not edit!
package com.example.cookingmagic.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.cookingmagic.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityOptionsBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final ImageView backButton;

  @NonNull
  public final TextView darkModeOption;

  @NonNull
  public final TextView favoritesTextView;

  @NonNull
  public final TextView languageSettingsOption;

  @NonNull
  public final TextView logOutOption;

  @NonNull
  public final ConstraintLayout main;

  @NonNull
  public final TextView recipesAddedTextView;

  @NonNull
  public final TextView userInitialsText;

  @NonNull
  public final TextView viewFavoritesOption;

  @NonNull
  public final TextView viewRecipesOption;

  private ActivityOptionsBinding(@NonNull ConstraintLayout rootView, @NonNull ImageView backButton,
      @NonNull TextView darkModeOption, @NonNull TextView favoritesTextView,
      @NonNull TextView languageSettingsOption, @NonNull TextView logOutOption,
      @NonNull ConstraintLayout main, @NonNull TextView recipesAddedTextView,
      @NonNull TextView userInitialsText, @NonNull TextView viewFavoritesOption,
      @NonNull TextView viewRecipesOption) {
    this.rootView = rootView;
    this.backButton = backButton;
    this.darkModeOption = darkModeOption;
    this.favoritesTextView = favoritesTextView;
    this.languageSettingsOption = languageSettingsOption;
    this.logOutOption = logOutOption;
    this.main = main;
    this.recipesAddedTextView = recipesAddedTextView;
    this.userInitialsText = userInitialsText;
    this.viewFavoritesOption = viewFavoritesOption;
    this.viewRecipesOption = viewRecipesOption;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityOptionsBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityOptionsBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_options, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityOptionsBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.backButton;
      ImageView backButton = ViewBindings.findChildViewById(rootView, id);
      if (backButton == null) {
        break missingId;
      }

      id = R.id.darkModeOption;
      TextView darkModeOption = ViewBindings.findChildViewById(rootView, id);
      if (darkModeOption == null) {
        break missingId;
      }

      id = R.id.favoritesTextView;
      TextView favoritesTextView = ViewBindings.findChildViewById(rootView, id);
      if (favoritesTextView == null) {
        break missingId;
      }

      id = R.id.languageSettingsOption;
      TextView languageSettingsOption = ViewBindings.findChildViewById(rootView, id);
      if (languageSettingsOption == null) {
        break missingId;
      }

      id = R.id.logOutOption;
      TextView logOutOption = ViewBindings.findChildViewById(rootView, id);
      if (logOutOption == null) {
        break missingId;
      }

      ConstraintLayout main = (ConstraintLayout) rootView;

      id = R.id.recipesAddedTextView;
      TextView recipesAddedTextView = ViewBindings.findChildViewById(rootView, id);
      if (recipesAddedTextView == null) {
        break missingId;
      }

      id = R.id.userInitialsText;
      TextView userInitialsText = ViewBindings.findChildViewById(rootView, id);
      if (userInitialsText == null) {
        break missingId;
      }

      id = R.id.viewFavoritesOption;
      TextView viewFavoritesOption = ViewBindings.findChildViewById(rootView, id);
      if (viewFavoritesOption == null) {
        break missingId;
      }

      id = R.id.viewRecipesOption;
      TextView viewRecipesOption = ViewBindings.findChildViewById(rootView, id);
      if (viewRecipesOption == null) {
        break missingId;
      }

      return new ActivityOptionsBinding((ConstraintLayout) rootView, backButton, darkModeOption,
          favoritesTextView, languageSettingsOption, logOutOption, main, recipesAddedTextView,
          userInitialsText, viewFavoritesOption, viewRecipesOption);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
