// Generated by view binder compiler. Do not edit!
package com.example.cookingmagic.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.cookingmagic.R;
import com.google.android.material.textfield.TextInputEditText;
import com.google.android.material.textfield.TextInputLayout;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivitySignupBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final TextView appNameTextView;

  @NonNull
  public final TextInputEditText confirmPasswordEditText;

  @NonNull
  public final TextInputLayout confirmPasswordInput;

  @NonNull
  public final TextInputEditText emailEditText;

  @NonNull
  public final TextInputLayout emailInputLayout;

  @NonNull
  public final TextView loginTextView;

  @NonNull
  public final ImageView logoImageView;

  @NonNull
  public final ConstraintLayout main;

  @NonNull
  public final TextInputEditText passwordEditText;

  @NonNull
  public final TextInputLayout passwordInputLayout;

  @NonNull
  public final Button signupButton;

  private ActivitySignupBinding(@NonNull ConstraintLayout rootView,
      @NonNull TextView appNameTextView, @NonNull TextInputEditText confirmPasswordEditText,
      @NonNull TextInputLayout confirmPasswordInput, @NonNull TextInputEditText emailEditText,
      @NonNull TextInputLayout emailInputLayout, @NonNull TextView loginTextView,
      @NonNull ImageView logoImageView, @NonNull ConstraintLayout main,
      @NonNull TextInputEditText passwordEditText, @NonNull TextInputLayout passwordInputLayout,
      @NonNull Button signupButton) {
    this.rootView = rootView;
    this.appNameTextView = appNameTextView;
    this.confirmPasswordEditText = confirmPasswordEditText;
    this.confirmPasswordInput = confirmPasswordInput;
    this.emailEditText = emailEditText;
    this.emailInputLayout = emailInputLayout;
    this.loginTextView = loginTextView;
    this.logoImageView = logoImageView;
    this.main = main;
    this.passwordEditText = passwordEditText;
    this.passwordInputLayout = passwordInputLayout;
    this.signupButton = signupButton;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivitySignupBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivitySignupBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_signup, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivitySignupBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.appNameTextView;
      TextView appNameTextView = ViewBindings.findChildViewById(rootView, id);
      if (appNameTextView == null) {
        break missingId;
      }

      id = R.id.confirmPasswordEditText;
      TextInputEditText confirmPasswordEditText = ViewBindings.findChildViewById(rootView, id);
      if (confirmPasswordEditText == null) {
        break missingId;
      }

      id = R.id.confirmPasswordInput;
      TextInputLayout confirmPasswordInput = ViewBindings.findChildViewById(rootView, id);
      if (confirmPasswordInput == null) {
        break missingId;
      }

      id = R.id.emailEditText;
      TextInputEditText emailEditText = ViewBindings.findChildViewById(rootView, id);
      if (emailEditText == null) {
        break missingId;
      }

      id = R.id.emailInputLayout;
      TextInputLayout emailInputLayout = ViewBindings.findChildViewById(rootView, id);
      if (emailInputLayout == null) {
        break missingId;
      }

      id = R.id.loginTextView;
      TextView loginTextView = ViewBindings.findChildViewById(rootView, id);
      if (loginTextView == null) {
        break missingId;
      }

      id = R.id.logoImageView;
      ImageView logoImageView = ViewBindings.findChildViewById(rootView, id);
      if (logoImageView == null) {
        break missingId;
      }

      ConstraintLayout main = (ConstraintLayout) rootView;

      id = R.id.passwordEditText;
      TextInputEditText passwordEditText = ViewBindings.findChildViewById(rootView, id);
      if (passwordEditText == null) {
        break missingId;
      }

      id = R.id.passwordInputLayout;
      TextInputLayout passwordInputLayout = ViewBindings.findChildViewById(rootView, id);
      if (passwordInputLayout == null) {
        break missingId;
      }

      id = R.id.signupButton;
      Button signupButton = ViewBindings.findChildViewById(rootView, id);
      if (signupButton == null) {
        break missingId;
      }

      return new ActivitySignupBinding((ConstraintLayout) rootView, appNameTextView,
          confirmPasswordEditText, confirmPasswordInput, emailEditText, emailInputLayout,
          loginTextView, logoImageView, main, passwordEditText, passwordInputLayout, signupButton);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
