// Generated by view binder compiler. Do not edit!
package com.example.cookingmagic.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.cookingmagic.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityTipFourBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final ImageView backButton;

  @NonNull
  public final ConstraintLayout main;

  @NonNull
  public final TextView tipDescriptionTextView;

  @NonNull
  public final ImageView tipImageView;

  @NonNull
  public final TextView tipTitleTextView;

  private ActivityTipFourBinding(@NonNull ConstraintLayout rootView, @NonNull ImageView backButton,
      @NonNull ConstraintLayout main, @NonNull TextView tipDescriptionTextView,
      @NonNull ImageView tipImageView, @NonNull TextView tipTitleTextView) {
    this.rootView = rootView;
    this.backButton = backButton;
    this.main = main;
    this.tipDescriptionTextView = tipDescriptionTextView;
    this.tipImageView = tipImageView;
    this.tipTitleTextView = tipTitleTextView;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityTipFourBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityTipFourBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_tip_four, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityTipFourBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.backButton;
      ImageView backButton = ViewBindings.findChildViewById(rootView, id);
      if (backButton == null) {
        break missingId;
      }

      ConstraintLayout main = (ConstraintLayout) rootView;

      id = R.id.tipDescriptionTextView;
      TextView tipDescriptionTextView = ViewBindings.findChildViewById(rootView, id);
      if (tipDescriptionTextView == null) {
        break missingId;
      }

      id = R.id.tipImageView;
      ImageView tipImageView = ViewBindings.findChildViewById(rootView, id);
      if (tipImageView == null) {
        break missingId;
      }

      id = R.id.tipTitleTextView;
      TextView tipTitleTextView = ViewBindings.findChildViewById(rootView, id);
      if (tipTitleTextView == null) {
        break missingId;
      }

      return new ActivityTipFourBinding((ConstraintLayout) rootView, backButton, main,
          tipDescriptionTextView, tipImageView, tipTitleTextView);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
