// Generated by view binder compiler. Do not edit!
package com.example.cookingmagic.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.cookingmagic.R;
import com.google.android.material.bottomnavigation.BottomNavigationView;
import com.google.android.material.textfield.TextInputEditText;
import com.google.android.material.textfield.TextInputLayout;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityHomeBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final ImageView accountIcon;

  @NonNull
  public final TextView appNameTextView;

  @NonNull
  public final ImageView bannerImageView;

  @NonNull
  public final BottomNavigationView bottomNavigation;

  @NonNull
  public final ImageView emptyListImageView;

  @NonNull
  public final ConstraintLayout main;

  @NonNull
  public final RecyclerView recipesRecyclerView;

  @NonNull
  public final TextView recipesSubheadingTextView;

  @NonNull
  public final TextInputEditText searchEditText;

  @NonNull
  public final TextInputLayout searchInputLayout;

  @NonNull
  public final RecyclerView storiesRecyclerView;

  @NonNull
  public final TextView tipsSubheadingTextView;

  @NonNull
  public final TextView welcomeTextView;

  private ActivityHomeBinding(@NonNull ConstraintLayout rootView, @NonNull ImageView accountIcon,
      @NonNull TextView appNameTextView, @NonNull ImageView bannerImageView,
      @NonNull BottomNavigationView bottomNavigation, @NonNull ImageView emptyListImageView,
      @NonNull ConstraintLayout main, @NonNull RecyclerView recipesRecyclerView,
      @NonNull TextView recipesSubheadingTextView, @NonNull TextInputEditText searchEditText,
      @NonNull TextInputLayout searchInputLayout, @NonNull RecyclerView storiesRecyclerView,
      @NonNull TextView tipsSubheadingTextView, @NonNull TextView welcomeTextView) {
    this.rootView = rootView;
    this.accountIcon = accountIcon;
    this.appNameTextView = appNameTextView;
    this.bannerImageView = bannerImageView;
    this.bottomNavigation = bottomNavigation;
    this.emptyListImageView = emptyListImageView;
    this.main = main;
    this.recipesRecyclerView = recipesRecyclerView;
    this.recipesSubheadingTextView = recipesSubheadingTextView;
    this.searchEditText = searchEditText;
    this.searchInputLayout = searchInputLayout;
    this.storiesRecyclerView = storiesRecyclerView;
    this.tipsSubheadingTextView = tipsSubheadingTextView;
    this.welcomeTextView = welcomeTextView;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityHomeBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityHomeBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_home, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityHomeBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.accountIcon;
      ImageView accountIcon = ViewBindings.findChildViewById(rootView, id);
      if (accountIcon == null) {
        break missingId;
      }

      id = R.id.appNameTextView;
      TextView appNameTextView = ViewBindings.findChildViewById(rootView, id);
      if (appNameTextView == null) {
        break missingId;
      }

      id = R.id.bannerImageView;
      ImageView bannerImageView = ViewBindings.findChildViewById(rootView, id);
      if (bannerImageView == null) {
        break missingId;
      }

      id = R.id.bottomNavigation;
      BottomNavigationView bottomNavigation = ViewBindings.findChildViewById(rootView, id);
      if (bottomNavigation == null) {
        break missingId;
      }

      id = R.id.emptyListImageView;
      ImageView emptyListImageView = ViewBindings.findChildViewById(rootView, id);
      if (emptyListImageView == null) {
        break missingId;
      }

      ConstraintLayout main = (ConstraintLayout) rootView;

      id = R.id.recipesRecyclerView;
      RecyclerView recipesRecyclerView = ViewBindings.findChildViewById(rootView, id);
      if (recipesRecyclerView == null) {
        break missingId;
      }

      id = R.id.recipesSubheadingTextView;
      TextView recipesSubheadingTextView = ViewBindings.findChildViewById(rootView, id);
      if (recipesSubheadingTextView == null) {
        break missingId;
      }

      id = R.id.searchEditText;
      TextInputEditText searchEditText = ViewBindings.findChildViewById(rootView, id);
      if (searchEditText == null) {
        break missingId;
      }

      id = R.id.searchInputLayout;
      TextInputLayout searchInputLayout = ViewBindings.findChildViewById(rootView, id);
      if (searchInputLayout == null) {
        break missingId;
      }

      id = R.id.storiesRecyclerView;
      RecyclerView storiesRecyclerView = ViewBindings.findChildViewById(rootView, id);
      if (storiesRecyclerView == null) {
        break missingId;
      }

      id = R.id.tipsSubheadingTextView;
      TextView tipsSubheadingTextView = ViewBindings.findChildViewById(rootView, id);
      if (tipsSubheadingTextView == null) {
        break missingId;
      }

      id = R.id.welcomeTextView;
      TextView welcomeTextView = ViewBindings.findChildViewById(rootView, id);
      if (welcomeTextView == null) {
        break missingId;
      }

      return new ActivityHomeBinding((ConstraintLayout) rootView, accountIcon, appNameTextView,
          bannerImageView, bottomNavigation, emptyListImageView, main, recipesRecyclerView,
          recipesSubheadingTextView, searchEditText, searchInputLayout, storiesRecyclerView,
          tipsSubheadingTextView, welcomeTextView);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
