// Generated by view binder compiler. Do not edit!
package com.example.cookingmagic.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.ScrollView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.cookingmagic.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivitySearchRecipeBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final ImageView backButton;

  @NonNull
  public final ConstraintLayout main;

  @NonNull
  public final ScrollView resultsScrollView;

  @NonNull
  public final TextView resultsTextView;

  @NonNull
  public final Button searchButton;

  @NonNull
  public final EditText searchEditText;

  private ActivitySearchRecipeBinding(@NonNull ConstraintLayout rootView,
      @NonNull ImageView backButton, @NonNull ConstraintLayout main,
      @NonNull ScrollView resultsScrollView, @NonNull TextView resultsTextView,
      @NonNull Button searchButton, @NonNull EditText searchEditText) {
    this.rootView = rootView;
    this.backButton = backButton;
    this.main = main;
    this.resultsScrollView = resultsScrollView;
    this.resultsTextView = resultsTextView;
    this.searchButton = searchButton;
    this.searchEditText = searchEditText;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivitySearchRecipeBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivitySearchRecipeBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_search_recipe, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivitySearchRecipeBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.backButton;
      ImageView backButton = ViewBindings.findChildViewById(rootView, id);
      if (backButton == null) {
        break missingId;
      }

      ConstraintLayout main = (ConstraintLayout) rootView;

      id = R.id.resultsScrollView;
      ScrollView resultsScrollView = ViewBindings.findChildViewById(rootView, id);
      if (resultsScrollView == null) {
        break missingId;
      }

      id = R.id.resultsTextView;
      TextView resultsTextView = ViewBindings.findChildViewById(rootView, id);
      if (resultsTextView == null) {
        break missingId;
      }

      id = R.id.searchButton;
      Button searchButton = ViewBindings.findChildViewById(rootView, id);
      if (searchButton == null) {
        break missingId;
      }

      id = R.id.searchEditText;
      EditText searchEditText = ViewBindings.findChildViewById(rootView, id);
      if (searchEditText == null) {
        break missingId;
      }

      return new ActivitySearchRecipeBinding((ConstraintLayout) rootView, backButton, main,
          resultsScrollView, resultsTextView, searchButton, searchEditText);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
