// Generated by view binder compiler. Do not edit!
package com.example.cookingmagic.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ScrollView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.cookingmagic.R;
import com.google.android.material.bottomnavigation.BottomNavigationView;
import com.google.android.material.button.MaterialButton;
import com.google.android.material.textfield.TextInputEditText;
import com.google.android.material.textfield.TextInputLayout;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityAddRecipieBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final MaterialButton addIngredientButton;

  @NonNull
  public final TextView addRecipeText;

  @NonNull
  public final BottomNavigationView bottomNavigation;

  @NonNull
  public final MaterialButton doneButton;

  @NonNull
  public final TextInputEditText ingredientNameEditText;

  @NonNull
  public final TextInputLayout ingredientNameInputLayout;

  @NonNull
  public final RecyclerView ingredientsRecyclerView;

  @NonNull
  public final TextView ingredientsSubheadingTextView;

  @NonNull
  public final ConstraintLayout main;

  @NonNull
  public final TextInputEditText quantityEditText;

  @NonNull
  public final TextInputLayout quantityInputLayout;

  @NonNull
  public final TextInputEditText recipeNameEditText;

  @NonNull
  public final TextInputLayout recipeNameInputLayout;

  @NonNull
  public final ScrollView scrollView;

  @NonNull
  public final TextInputEditText unitEditText;

  @NonNull
  public final TextInputLayout unitInputLayout;

  private ActivityAddRecipieBinding(@NonNull ConstraintLayout rootView,
      @NonNull MaterialButton addIngredientButton, @NonNull TextView addRecipeText,
      @NonNull BottomNavigationView bottomNavigation, @NonNull MaterialButton doneButton,
      @NonNull TextInputEditText ingredientNameEditText,
      @NonNull TextInputLayout ingredientNameInputLayout,
      @NonNull RecyclerView ingredientsRecyclerView,
      @NonNull TextView ingredientsSubheadingTextView, @NonNull ConstraintLayout main,
      @NonNull TextInputEditText quantityEditText, @NonNull TextInputLayout quantityInputLayout,
      @NonNull TextInputEditText recipeNameEditText, @NonNull TextInputLayout recipeNameInputLayout,
      @NonNull ScrollView scrollView, @NonNull TextInputEditText unitEditText,
      @NonNull TextInputLayout unitInputLayout) {
    this.rootView = rootView;
    this.addIngredientButton = addIngredientButton;
    this.addRecipeText = addRecipeText;
    this.bottomNavigation = bottomNavigation;
    this.doneButton = doneButton;
    this.ingredientNameEditText = ingredientNameEditText;
    this.ingredientNameInputLayout = ingredientNameInputLayout;
    this.ingredientsRecyclerView = ingredientsRecyclerView;
    this.ingredientsSubheadingTextView = ingredientsSubheadingTextView;
    this.main = main;
    this.quantityEditText = quantityEditText;
    this.quantityInputLayout = quantityInputLayout;
    this.recipeNameEditText = recipeNameEditText;
    this.recipeNameInputLayout = recipeNameInputLayout;
    this.scrollView = scrollView;
    this.unitEditText = unitEditText;
    this.unitInputLayout = unitInputLayout;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityAddRecipieBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityAddRecipieBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_add_recipie, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityAddRecipieBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.addIngredientButton;
      MaterialButton addIngredientButton = ViewBindings.findChildViewById(rootView, id);
      if (addIngredientButton == null) {
        break missingId;
      }

      id = R.id.addRecipeText;
      TextView addRecipeText = ViewBindings.findChildViewById(rootView, id);
      if (addRecipeText == null) {
        break missingId;
      }

      id = R.id.bottomNavigation;
      BottomNavigationView bottomNavigation = ViewBindings.findChildViewById(rootView, id);
      if (bottomNavigation == null) {
        break missingId;
      }

      id = R.id.doneButton;
      MaterialButton doneButton = ViewBindings.findChildViewById(rootView, id);
      if (doneButton == null) {
        break missingId;
      }

      id = R.id.ingredientNameEditText;
      TextInputEditText ingredientNameEditText = ViewBindings.findChildViewById(rootView, id);
      if (ingredientNameEditText == null) {
        break missingId;
      }

      id = R.id.ingredientNameInputLayout;
      TextInputLayout ingredientNameInputLayout = ViewBindings.findChildViewById(rootView, id);
      if (ingredientNameInputLayout == null) {
        break missingId;
      }

      id = R.id.ingredientsRecyclerView;
      RecyclerView ingredientsRecyclerView = ViewBindings.findChildViewById(rootView, id);
      if (ingredientsRecyclerView == null) {
        break missingId;
      }

      id = R.id.ingredientsSubheadingTextView;
      TextView ingredientsSubheadingTextView = ViewBindings.findChildViewById(rootView, id);
      if (ingredientsSubheadingTextView == null) {
        break missingId;
      }

      ConstraintLayout main = (ConstraintLayout) rootView;

      id = R.id.quantityEditText;
      TextInputEditText quantityEditText = ViewBindings.findChildViewById(rootView, id);
      if (quantityEditText == null) {
        break missingId;
      }

      id = R.id.quantityInputLayout;
      TextInputLayout quantityInputLayout = ViewBindings.findChildViewById(rootView, id);
      if (quantityInputLayout == null) {
        break missingId;
      }

      id = R.id.recipeNameEditText;
      TextInputEditText recipeNameEditText = ViewBindings.findChildViewById(rootView, id);
      if (recipeNameEditText == null) {
        break missingId;
      }

      id = R.id.recipeNameInputLayout;
      TextInputLayout recipeNameInputLayout = ViewBindings.findChildViewById(rootView, id);
      if (recipeNameInputLayout == null) {
        break missingId;
      }

      id = R.id.scrollView;
      ScrollView scrollView = ViewBindings.findChildViewById(rootView, id);
      if (scrollView == null) {
        break missingId;
      }

      id = R.id.unitEditText;
      TextInputEditText unitEditText = ViewBindings.findChildViewById(rootView, id);
      if (unitEditText == null) {
        break missingId;
      }

      id = R.id.unitInputLayout;
      TextInputLayout unitInputLayout = ViewBindings.findChildViewById(rootView, id);
      if (unitInputLayout == null) {
        break missingId;
      }

      return new ActivityAddRecipieBinding((ConstraintLayout) rootView, addIngredientButton,
          addRecipeText, bottomNavigation, doneButton, ingredientNameEditText,
          ingredientNameInputLayout, ingredientsRecyclerView, ingredientsSubheadingTextView, main,
          quantityEditText, quantityInputLayout, recipeNameEditText, recipeNameInputLayout,
          scrollView, unitEditText, unitInputLayout);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
