// Generated by view binder compiler. Do not edit!
package com.example.cookingmagic.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.cardview.widget.CardView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.cookingmagic.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class IngredientLayoutCardBinding implements ViewBinding {
  @NonNull
  private final CardView rootView;

  @NonNull
  public final View divider;

  @NonNull
  public final TextView ingredientNameTextView;

  @NonNull
  public final LinearLayout quantityContainer;

  @NonNull
  public final TextView quantityValueTextView;

  @NonNull
  public final TextView unitMeasureTextView;

  private IngredientLayoutCardBinding(@NonNull CardView rootView, @NonNull View divider,
      @NonNull TextView ingredientNameTextView, @NonNull LinearLayout quantityContainer,
      @NonNull TextView quantityValueTextView, @NonNull TextView unitMeasureTextView) {
    this.rootView = rootView;
    this.divider = divider;
    this.ingredientNameTextView = ingredientNameTextView;
    this.quantityContainer = quantityContainer;
    this.quantityValueTextView = quantityValueTextView;
    this.unitMeasureTextView = unitMeasureTextView;
  }

  @Override
  @NonNull
  public CardView getRoot() {
    return rootView;
  }

  @NonNull
  public static IngredientLayoutCardBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static IngredientLayoutCardBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.ingredient_layout_card, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static IngredientLayoutCardBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.divider;
      View divider = ViewBindings.findChildViewById(rootView, id);
      if (divider == null) {
        break missingId;
      }

      id = R.id.ingredientNameTextView;
      TextView ingredientNameTextView = ViewBindings.findChildViewById(rootView, id);
      if (ingredientNameTextView == null) {
        break missingId;
      }

      id = R.id.quantityContainer;
      LinearLayout quantityContainer = ViewBindings.findChildViewById(rootView, id);
      if (quantityContainer == null) {
        break missingId;
      }

      id = R.id.quantityValueTextView;
      TextView quantityValueTextView = ViewBindings.findChildViewById(rootView, id);
      if (quantityValueTextView == null) {
        break missingId;
      }

      id = R.id.unitMeasureTextView;
      TextView unitMeasureTextView = ViewBindings.findChildViewById(rootView, id);
      if (unitMeasureTextView == null) {
        break missingId;
      }

      return new IngredientLayoutCardBinding((CardView) rootView, divider, ingredientNameTextView,
          quantityContainer, quantityValueTextView, unitMeasureTextView);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
