// Generated by view binder compiler. Do not edit!
package com.example.cookingmagic.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.cardview.widget.CardView;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.cookingmagic.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class RecipeLayoutCardBinding implements ViewBinding {
  @NonNull
  private final CardView rootView;

  @NonNull
  public final View divider;

  @NonNull
  public final ImageView favoriteIcon;

  @NonNull
  public final RecyclerView ingredientsRecyclerView;

  @NonNull
  public final TextView ingredientsSubheadingTextView;

  @NonNull
  public final TextView recipeNameTextView;

  private RecipeLayoutCardBinding(@NonNull CardView rootView, @NonNull View divider,
      @NonNull ImageView favoriteIcon, @NonNull RecyclerView ingredientsRecyclerView,
      @NonNull TextView ingredientsSubheadingTextView, @NonNull TextView recipeNameTextView) {
    this.rootView = rootView;
    this.divider = divider;
    this.favoriteIcon = favoriteIcon;
    this.ingredientsRecyclerView = ingredientsRecyclerView;
    this.ingredientsSubheadingTextView = ingredientsSubheadingTextView;
    this.recipeNameTextView = recipeNameTextView;
  }

  @Override
  @NonNull
  public CardView getRoot() {
    return rootView;
  }

  @NonNull
  public static RecipeLayoutCardBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static RecipeLayoutCardBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.recipe_layout_card, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static RecipeLayoutCardBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.divider;
      View divider = ViewBindings.findChildViewById(rootView, id);
      if (divider == null) {
        break missingId;
      }

      id = R.id.favoriteIcon;
      ImageView favoriteIcon = ViewBindings.findChildViewById(rootView, id);
      if (favoriteIcon == null) {
        break missingId;
      }

      id = R.id.ingredientsRecyclerView;
      RecyclerView ingredientsRecyclerView = ViewBindings.findChildViewById(rootView, id);
      if (ingredientsRecyclerView == null) {
        break missingId;
      }

      id = R.id.ingredientsSubheadingTextView;
      TextView ingredientsSubheadingTextView = ViewBindings.findChildViewById(rootView, id);
      if (ingredientsSubheadingTextView == null) {
        break missingId;
      }

      id = R.id.recipeNameTextView;
      TextView recipeNameTextView = ViewBindings.findChildViewById(rootView, id);
      if (recipeNameTextView == null) {
        break missingId;
      }

      return new RecipeLayoutCardBinding((CardView) rootView, divider, favoriteIcon,
          ingredientsRecyclerView, ingredientsSubheadingTextView, recipeNameTextView);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
